version: '3.6'

networks:
  # network for all services
  crlsn:
    driver: bridge
services:
  nginx:
    image: jwilder/nginx-proxy
    networks:
      crlsn:
        aliases:
          - nthn.crlsn.io.localhost

    ports:
      - '443:443'
    restart: always
    volumes:
      - '/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './certs:/etc/nginx/certs'
      - './projects/nginx-proxy/overrides.conf:/etc/nginx/conf.d/overrides.conf'
