version: '3.6'
services:

  postgres:
    environment:
      POSTGRES_USER: crlsn
      POSTGRES_PASSWORD: nthn_crlsn_io
      POSTGRES_DB: crlsn
    image: postgres

  # web:
  #   hostname: api
  #   image: nscarlson/crlsn-api
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - mongo1:mongo1
  #   restart: always

  nginx:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - '/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './certs:/etc/nginx/certs'
      - './packages/nginx/overrides.conf:/etc/nginx/conf.d/overrides.conf'
