# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            yarn
            echo ${NOW_TOKEN}

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Deploy to now.sh

          command: yarn now -t ${NOW_TOKEN} alias crlsn.now.sh nthn.crlsn.io

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
